// property-string/ng-prop-string/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

import { propertyStringPathFactory } from 'property-string-path';
import { User } from './models/user';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  public title = 'ng-prop-string';
  public form: FormGroup;

  public controlPath = propertyStringPathFactory<User>();

  constructor(private fb: FormBuilder) {}

  public ngOnInit(): void {
    this.form = this.fb.group({
      id: '',
      name: '',
      username: '',
      email: '',
      phone: '',
      website: '',
      company: this.fb.group({
        name: '',
        catchPhrase: '',
        bs: '',
      }),
      address: this.fb.group({
        street: '',
        suite: '',
        city: '',
        zipcode: '',
        geo: this.fb.group({
          lat: '',
          lng: '',
        }),
      }),
    });

    this.form.get(this.controlPath('address.geo.lat')).valueChanges.subscribe(console.log);
  }
}

<form [formGroup]="form">
  <input [formControl]="form.get(controlPath('address.geo.lat'))" />
</form>

// property-string/cra-prop-string/src/App.tsx
import { useEffect } from 'react';

import { useForm } from 'react-hook-form';
import { propertyStringPathFactory } from 'property-string-path';

import { User } from './user.model';
import './App.css';

export const App = () => {
  const formKeys = propertyStringPathFactory<User>();
  const { register, watch } = useForm<User>();

  const lat = watch(formKeys('address.geo.lat'));

  useEffect(() => {
    console.log(lat);
  }, [lat]);

  return (
    <div className="App">
      <form>
        <input name={formKeys('address.geo.lat')} ref={register} />
      </form>
    </div>
  );
};
